### ISSUE TITLE
Suspected mistakes in the documentation and the paper

### ISSUE THREAD

**Issue by AndrewYY** [WMiller256/Alhazen-Ptolemy#1]
I believe the definitions of `c` and `b` are reversed in the README, owing to the fact that in definitions:
```python
t1 = np.arctan2(b * np.sin(obs) - rt * np.sin(spec), b * np.cos(obs) - rt * np.cos(spec))
t2 = np.arctan2(c * np.sin(src) - rt * np.sin(spec), c * np.cos(src) - rt * np.cos(spec))
```
the angles t1 and t2 correspond to the angles from the specular point to the observer/source, where b must correspond to the radius to the observer, and c to the radius of the source.

This same mistake (mixing up Rsrc and Robs) seems to be present in https://arxiv.org/pdf/2012.02170.pdf equation 17 on page 6 (I don't know if this is the latest revision of the paper or if it was subsequently corrected)

The definitions in the C code comments appear to be correct, although I did not test the C implementation.

As an aside, I also find disagreement between `numerical` and `branchdeducing_twofinite` for the inputs:
`obs=-0.2989068116739271 c=0.3380059593586045 b=0.21900854161140168` although this seems like a deeper issue. The 3rd branch is chosen but the numerical solution agrees with the second branch.

**Comment by WMiller256** [comment]
Thank you for bringing this to my attention, I will update the documentation. I will also include a link to the most up-to-date version of the paper.

To your aside, I made a fundamental assumption when I composed the branch-deduction of which I was unaware until you raised this issue: that the nearer of the source and observer would be the one rotated to `pi / 2`. Hence, `b` must be greater than or equal to `c` or the inverse tangent fails. I'm not sure what the correct limits `L1` and `L2` should be when `c > b`. 

Since the Euler rotation can always be chosen to place the correct point at `pi / 2`, I'm going to leave that up to the reader's efforts, if they are so inclined.
